#mysql dane dostepowe
#username: root
#password: ananas

development:
  adapter: mysql2
  encoding: utf8
  database: konisie-dev1_development
  pool: 5
  username: root
  password: ananas
  host: localhost


test:
  adapter: mysql2
  encoding: utf8
  database: konisie-dev1_test
  pool: 5
  username: root
  password: ananas
  host: localhost


production:
  adapter: postgresql
  encoding: unicode
  database: konisie-dev1_production
  pool: 5
  username: postgres
  password: ananas
  host: localhost
